<?php
function formfit_init() {

    drupal_add_library( 'system', 'drupal.ajax' );

  }
/**
 * Implementation of hook_block_info().
**/
function formfit_block_info() {
  $blocks = array();
  $blocks['custom_footer'] = array(
    'info'  => t('footer formfit'),
    'cache' => DRUPAL_CACHE_GLOBAL,
    );
  $blocks['compare'] = array(
    'info'  => t('Compare-custom'),
    'cache' => DRUPAL_CACHE_GLOBAL,
    );
  return $blocks;
}

/**
 * Implementation of hook_menu().
 */
function formfit_menu(){
  /*$items['compare'] = array(
    'title'            => t('Compare'),
    'description'      => t('Form config video home'),
    'page callback'    => '_formfit',
    'access arguments' => array('access content'),
    'file'             => 'inc/formfit.pages.inc',
    'type'             => MENU_NORMAL_ITEM,
    );*/
  $items['formfit-compare/add/%'] = array(
    'access arguments' => array('access content'),
    'page arguments'   => array(2),
    'page callback'    => 'formfit_product_add',
    'file'             => 'inc/formfit.pages.inc',
    'title'            => t('Adicionar Proyecto'),
    'type'             => MENU_CALLBACK,
  );

  $items['formfit-compare/remove/%'] = array(
    'access arguments' => array('access content'),
    'page arguments'   => array(2),
    'page callback'    => 'formfit_product_remove',
    'file'             => 'inc/formfit.pages.inc',
    'title'            => t('Adicionar Proyecto'),
    'type'             => MENU_CALLBACK,
  );
    return $items;
}

/**
 * Implementation of hook_block_view().
 */
/**
 * Implementation of hook_block_view().
 * @param  string $delta [description]
 * @return [type]        [description]
 */
function formfit_block_view($delta = '') {
    $block = array();
    switch ($delta) {
      case 'custom_footer':
        $block['title'] = '<none>';
        $information    = menu_tree('menu-informacion');
        $client_services= menu_tree('menu-servicio-al-cliente');
        $news_letter    = module_invoke('webform','block_view','client-block-78');
        $block['content'] =array(
                  '#theme' => 'custom_footer',
                  '#items' => array($information, $client_services, $news_letter),
                  );
      break;
      case 'compare':
        $block['subject'] = t('Comparar-custom');
        $block['content'] = formfit_bottons_render();
      break;
    }
  return $block;
}

/**
 * Implementation of hook_theme().
*/
function formfit_theme(){
  return array(
  'custom_footer' => array(
            'template' => 'theme/custom_footer',
            'variables' => array(
                'items' => array(),
          )
        ),
  'formfit'=> array(
            'template' => 'theme/formfit',
            'variables' => array(
                'items' => array(),
          )
        ),
    );
}

/**
 * Implements block_view_alter
 */
function formfit_block_view_alter(&$data, $block) {
  if ($block->module == 'commerce_cart' && $block->delta == 'cart') {
    global $user;
    if ($order = commerce_cart_order_load($user->uid)) {
      // Count the number of product line items on the order.
      $wrapper = entity_metadata_wrapper('commerce_order', $order);
      $quantity = commerce_line_items_quantity($wrapper->commerce_line_items, commerce_product_line_item_types());

      // If there are more than 0 product line items on the order...
      if ($quantity > 0) {
        // Use the dynamic menu item title.
        $data['subject'] = $quantity;
      }else{
        // Use the dynamic menu item title.
        $data['subject'] = 0;
      }
    }

  }
}
/**
   *
   * formfit_bottons_render().
   *
   * function to render 2 bottons ...
   *
   * @return string $output width content from block.
   *
   */

  function formfit_bottons_render() {

    if ( !isset($_SESSION) ) { session_start(); }

    $productCompare = isset($_SESSION['productCompare']) ? $_SESSION['productCompare'] : array();
    $nId             = is_numeric( arg(1) ) ? arg(1) : null;
    $output          = '';

    if ( count($productCompare) === 4 || in_array(arg(1), $productCompare) ) {
      $linkCompare = l(t('›‹ comparar'), 'formfit-compare/add/'. $nId . '', array('attributes' => array('class' => array('link-compare', 'disable'))));
    } else {
      $linkCompare = l(t('›‹ comparar'), 'formfit-compare/add/'. $nId . '', array('attributes' => array('class' => array('link-compare', 'active', 'use-ajax'))));
    }

    $output .= '<div class="content-compare">';
    $output .=  $linkCompare;
    $output .= '</div>';

    $output .= '<div class="content-link-redirect">';
    $output .=  l(t('Lista de comparación (@count) ›', array('@count' => count($productCompare))), 'comparar', array('attributes' => array('class' => array('link-list-compare'))));
    $output .= '</div>';

    return $output;

  }

  function formfit_views_api() {

    return array(
        'api'  => 3,
        'path' => drupal_get_path( 'module',  'formfit' )
    );

  }
?>
